src/components/LandingPage.js

Should I also change the styling? I haven't because it was mentioned. Let me know if you also want to change me the styling of link on the landing page

Added link to editor page on landing page

---

package.json
src/components/CircularLoading.css
src/components/CircularLoading.js
src/components/LandingPage.js
src/components/Stars.js
src/hooks/useGetStars.js

what I have done :
1. Circular loading component with styles added
2. useGetStars custom hook for fetching stars added with providing fetchStates( loading, error, errorMessage, repositoryStars )
3. Stars component added with style with usage of useGetStars
4. Stars component added to landing page 
**Fulfilled case**
**Pending case**
**Rejected case**
I have followed your project code style but I highly recommend not using styles in JS because it will make your project less maintainable, scalable, and testable.
If you have any questions feel free to ask, otherwise let me know you are satisfied by the implementation by merging this PR,
thanks, skyDe

GitHub stars added to project

---

src/components/EditorComponent.js

fixes #9 
I have made dropdown logic reusable
IMO:- I think we should use MUI library for components which will give us some styling as well, let me know what do you think, if you want I can integrate MUI in this project.
@DhanushNehru

changed languages dropdown option logic into reusable

---

src/components/EditorComponent.js

fixes #21 
I am removing value from state when screen changes

fix screen should be empty while navigating languages

---

src/components/EditorComponent.js

fixes #26 
I have changes attributes name for components, hence solved the warnings

fixed invalid dom property warnings

---

package-lock.json
package.json
public/sitemap.xml
src/components/js/Stars.js
src/components/js/sitemapGenerator.js
src/components/js/sitemapRoutes.js
src/pages/EditorComponent.js

Website SEO improved by adding sitemap.

Add sitemap

---

package.json
src/App.js
src/theme.js

Installed MUI core library and integrated to project

---

.gitignore
README.md
t.env

update:Readme inclusion of request limit

---

.eslintrc.json
.gitignore
package.json
src/App.js
src/components/js/CircularLoading.js
src/components/js/Stars.js
src/components/js/sitemapGenerator.js
src/components/js/sitemapRoutes.js
src/pages/EditorComponent.js
src/pages/LandingPage.js
src/theme.js

fixes #10 
Added eslint functionality and some predefined roles
Also ran lint:fix fix the predefined rules

Implented eslint feature in project

---

src/hooks/useGetStars.js
src/pages/EditorComponent.js

Fixes #46
In this PR removes all console.log statements from the codebase as per issue #46.

Remove all console.log statements

---

README.md

fixes #1 
Added steps for setup of RapidAPI and JudgeO

added steps for rapidapi or judge0 setup in readme.md

---

src/pages/EditorComponent.js

fixes #47 
Added error handling for wrong code submission, now it willl throw error 'Please check the code' if there is wrong code submission
Demo:-

fixed wrong code error handling

---

.gitignore
package-lock.json
src/pages/EditorComponent.js

This PR contains code for execution for C++ code. 
#23

feat: Cpp code execution

---

src/constants/constants.js
src/pages/EditorComponent.js

fixes #54 
I created a new folder and file named `constants.js` to keep track of constant variables. This will help us reuse these variables easily and facilitate changes to these variables in a single location.

added constants file for all constants in code

---

package-lock.json
src/pages/EditorComponent.js

feat:50 requests per day limit prompt

---

src/pages/EditorComponent.js

feat: prepopulated Code Templates

---

src/constants/constants.js
src/pages/EditorComponent.js

this PR has included JAVA prepopulated code template after updating the main branch
#58

feat: updated code Templates

---

.eslintrc.json
src/App.js
src/components/js/Stars.js
src/components/js/sitemapGenerator.js

fixed eslint line break warning and updated eslint file

---

.github/pull_request_template.md

fixes #67 
I have added a pull_request_template.md file to prompt users to review essential steps before submitting a pull request.

Added pull request template file in .github

---

src/components/js/LanguageSelect.js
src/pages/EditorComponent.js

Resolves #69  
- 1 Implemented MUI autocomplete dropdown
- 2 Change user interface of existing dropdown

implemented autocomplete dropdown for basic language dropdown

---

.dockerignore
.env.example
Dockerfile
docker-compose.yml

Resolves #74 
1. Added `Dockerfile` to create an image of our project for containerization.
2. Added `docker-compose.yml` file for quick project initialization.

Added Dockerfile and Docker Compose files for project initialization.

---

README.md

Resolves #74 
- 1 Added steps for running project with docker in `readme.md`

Added steps for running project with docker in `readme.md`

---

src/components/css/index.css
src/theme.js

Resolves #[Issue Number if there] 
- 1
- 2

Change font

---

src/components/css/EditorComponent.css
src/pages/EditorComponent.js

Resolves #22 
- 1 changing editor layout with editor page component - EditorComponent.js
- 2 add two more style class - EditorComponent.css

change styled layout

---

public/index.html

Edit noscript phrase

---

public/robots.txt

Edit robots.txt

---

public/index.html

Edit theme color

---

src/components/css/EditorComponent.css

Change output theme

---

package-lock.json
package.json
src/App.js
src/components/css/EditorComponent.css
src/components/js/ToggleTheme.js
src/pages/EditorComponent.js
src/theme.js

**Submitting for Hacktoberfest'24**
Resolves #95
Added dark / light theme option using MUI `useColorScheme` hook
- [] I assure there is no similar/duplicate pull request regarding same issue

feat: added theme toggle option

---

package-lock.json
package.json
src/components/js/EditorThemeSelect.js
src/components/js/ToggleTheme.js
src/components/js/defineEditorTheme.js
src/constants/constants.js
src/pages/EditorComponent.js

**Submitting for Hacktoberfest'24**
Resolves #12 
Added theme selection for the editor using monaco-themes

feat: added theme selection for editor

---

src/components/js/Stars.js
src/constants/constants.js

Update stars style

---

src/components/js/ToggleTheme.js
src/pages/EditorComponent.js
src/theme.js

Edit editor style

---

src/pages/EditorComponent.js

fix: Code Disappears When Selecting the Same Language Twice

---

README.md

Add contributors image

---

src/components/Footer.js
src/components/IconButton.js
src/pages/EditorComponent.js

Resolves #127 
#127 
- [ x ] I have pull latest changes from `main` branch
- [ x ] I have tested the changes locally
- [ x ] I have run `npm run lint:fix` locally
- [ x ] I have performed a self-review of my code
- [ x ] I assure there is no similar/duplicate pull request regarding same issue
https://github.com/user-attachments/assets/21c1e41e-a64d-4d57-b224-12c66086c76a

icons added similar to the video

---

README.md
package-lock.json
package.json
src/components/js/Stars.js
src/hooks/useGetStars.js

Resolves #142 
- 1 Improved the GitHub authentication configuration details in the README to be more comprehensive and user-friendly.
- 2 Enhanced clarity and structure of instructions related to GitHub authentication, surpassing the previous merged PR.
Additional Context:
This PR builds upon the previous work done in a merged PR for the same issue. While the earlier PR was merged, I identified areas where the explanation could be clearer and more accessible for users. As a result, I have refined and expanded the details of the GitHub authentication configuration in the README.

Enhanced GitHub Authentication Details in README for Improved Clarity and Usability

---

package-lock.json
src/components/js/ToggleTheme.js
src/hooks/useGetStars.js

Resolves #151 
- 1 fixed the toggle button state mismatch
- 2 updated dev dependencies

fixed toggle button state mismatch

---

src/pages/EditorComponent.js

Resolves #152 
- 1 added one shortcut ctrl + enter for code submission

added ctrl + enter shortcut for code submission

---

package-lock.json
package.json
src/components/Footer.js

Resolves #180 
Added social media sharing functionality using `react-share`.

feat: added share feature in footer

---

.github/workflows/issue-auto-reply.yml

Resolves #[192] 
- 1Add automated welcome message bot for new issues

Add automated welcome message for new issues
